# Partner program cards
partner_program_cards_enabled = true
partner_program_cards_enabled = ${?PARTNER_PROGRAM_CARDS_ENABLED}

# URLs with program slug
program_slug_urls_enabled = false
program_slug_urls_enabled = ${?PROGRAM_SLUG_URLS_ENABLED}

